version: '2.1'

services:
  db:
    build: ./database/
    restart: always
    environment:
      - POSTGRES_USER=elo_api
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=elo_api
  api:
    build: .
    image: elo-api
    restart: always
    volumes:
      - .:/app:Z
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=elo_api
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=elo_api
