version: '2.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: abc123
  api:
    build: .
    image: elo-api
    restart: always
    volumes:
      - .:/app:Z
    ports:
      - 5000:5000
